# Generated by Django 5.1.3 on 2024-11-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_core', '0003_alter_galeryimage_image'),
        ('users', '0003_customuser_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='publications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_core.publication'),
        ),
    ]
