# Generated by Django 5.1.3 on 2024-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customfollower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_image',
            field=models.ImageField(blank=True, default='images/profile_img.jpg', null=True, upload_to=''),
        ),
    ]
