# Generated by Django 5.1.3 on 2024-12-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='publications',
        ),
    ]
