# Generated by Django 5.1.3 on 2024-12-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='describtion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
