# Generated by Django 5.1.3 on 2024-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_core', '0002_galeryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
