# Generated by Django 5.1.3 on 2024-12-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_core', '0005_publication_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='like',
        ),
    ]
